Test modifying jcpipeline check environments variables

diff --git a/.github/workflows/jcpipeline.yml b/.github/workflows/jcpipeline.yml
--- a/.github/workflows/jcpipeline.yml
+++ b/.github/workflows/jcpipeline.yml
@@ -9,6 +9,23 @@ on:
 
 jobs:
 
+  check_environment:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Environment Variables
+        env:
+          DB_HOST: ${{ secrets.DB_HOST }}
+          DB_USER: ${{ secrets.DB_USER }}
+          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+          DB_NAME: ${{ secrets.DB_NAME }}
+        run: |
+          if [[ -z "$DB_HOST" || -z "$DB_USER" || -z "$DB_PASSWORD" || -z "$DB_NAME" ]]; then
+            echo "One or more required environment variables are not set."
+            exit 1
+          else
+            echo "All required environment variables are set."
+          fi
+
   avoid_reduncy:
     runs-on: ubuntu-latest
     steps:
